/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: curiositysphere (https://sketchfab.com/curiositysphere)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cloud-sun-lowpoly-432217560dbf461c83faa027d077de07
title: Cloud & Sun Lowpoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cloud.gltf')
 
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[-66.19, 0, -0.16]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group name="Sphere001" position={[-900, 350, -1459.24]} rotation={[-Math.PI / 2, 0, 0]} scale={-299.54}>
                  <mesh geometry={nodes.Sphere001_sun_0.geometry} material={materials.material} />
                </group>
                <group position={[-124.1, 49.94, -1076.51]} rotation={[-Math.PI / 2, 0, 1.34]} scale={100}>
                  <mesh geometry={nodes.Cloud001__0.geometry} material={materials['Cloud.001__0']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cloud.gltf')
