/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lenovo-thinkpad-t590-68717a7905914b56a718945435c0fb22
title: Lenovo ThinkPad T590
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/thinkpad.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={0.1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[8.1, 7.4, 8]} rotation={[Math.PI / 8, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['thinkpad_lid_corner.png']} />
          </group>
          <group position={[8, 8, 8]}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['thinkpad_case_corner.png']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/thinkpad.gltf')
